const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cfg=window.SALES_OS_SUPABASE||{};
const sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let bootstrap={leads:[],meta:{}},feed={leads:[],meta:{}},scripts=[],replyPlaybook={},pipeline=JSON.parse(localStorage.getItem('growthPipelineCache')||'{}'),pending=JSON.parse(localStorage.getItem('growthPipelinePending')||'[]'),me=null,masterLoaded=false;
const STAGES=['Contact Ready','Contacted','Replied','Negotiating','Won/Paid','Fulfilled','Follow-up','Lost/Not a Fit','Do Not Contact'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=l=>String(l.id||l.record_id||l.business).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180);
function cache(){localStorage.setItem('growthPipelineCache',JSON.stringify(pipeline));localStorage.setItem('growthPipelinePending',JSON.stringify(pending))}
function stageFromMaster(v){const x=String(v||'Contact Ready');return ({'Attempted to Contact':'Contacted','Connected':'Contacted','Paid':'Won/Paid','Start Scheduled':'Won/Paid','Lost / Not a Fit':'Lost/Not a Fit'})[x]||STAGES.includes(x)?(({'Attempted to Contact':'Contacted','Connected':'Contacted','Paid':'Won/Paid','Start Scheduled':'Won/Paid','Lost / Not a Fit':'Lost/Not a Fit'})[x]||x):'Contact Ready'}
function st(l){return pipeline[key(l)]||{stage:stageFromMaster(l.stage||l.status),notes:l.user_notes||''}}
function setSync(text,state='idle'){ $('#syncStatus').textContent=text; $('#syncDot').className=`sync-dot ${state}`; $('#persistenceStatus').textContent=text }
function fill(t,l){return String(t||'').replaceAll('{business}',l.business||'this business')}
function productPrompt(l){return `Create the finished Same-Day Customer Growth Pack for ${l.business}. Use only the verified facts below and do not invent results, customers, testimonials, discounts, availability, or claims.\n\nIndustry/service: ${l.category||''}\nLocation: ${l.city||''}\nVerified evidence: ${l.evidence||l.opportunity||''}\nSpecific opportunity: ${l.opportunity||''}\nService focus: ${l.service_focus||''}\nSource: ${l.source||''}\n\nDeliver: 10 ready-to-post Google/social posts, 5 customer FAQs with answers, 3 estimate/customer follow-ups, 5 genuine review-request/reply templates, 5 CTA variations, 1 promotional email, 1 reactivation message, and a 30-day use plan. Keep the copy specific, useful, ethical, and ready to paste. Label any inference as an idea rather than a fact.`}
function normalizeMaster(l){return {...l,id:l.record_id,rank:l.master_rank,tier:l.verification_tier||l.lead_type,category:l.industry,reachability:l.signal||l.forecast_reply||'',initial:l.initial_email||'',source:l.source_url||l.website||'',verified:l.verification_date||'',stage:stageFromMaster(l.stage||l.status),status:stageFromMaster(l.stage||l.status),chatgpt_prompt:productPrompt({...l,category:l.industry,source:l.source_url||l.website||''})}}
async function gunzipBase64(b64){if(!('DecompressionStream'in window))throw new Error('This browser cannot decompress the private Sales OS dataset. Update Chrome/Edge and retry.');const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const stream=new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}
async function loadPrivateMaster(){if(!me)return false;setSync('Loading private Sales OS master…','busy');const {data,error}=await sb.from('sales_os_dataset_parts').select('part_no,payload_b64,record_count,sha256,updated_at').eq('dataset_key','sales-os-master-deploy').order('part_no');if(error)throw error;if(!data?.length||!data.some(x=>x.payload_b64))return false;const master=await gunzipBase64(data.map(x=>x.payload_b64||'').join(''));feed={meta:{...master.meta,lastUpdated:master.meta.generated,sourceOfTruth:'Private owner Sales OS master'},leads:(master.leads||[]).map(normalizeMaster)};replyPlaybook=master.reply_playbook||{};masterLoaded=true;$('#lastUpdated').textContent=`${feed.meta.lastUpdated} • ${feed.leads.length} owner-private records`;return true}
async function authState(){const {data:{session}}=await sb.auth.getSession();me=session?.user||null;setSync(me?`Supabase synced as ${me.email}`:'Sign in to load the private 981-record master',me?'ok':'warn')}
async function loadRemotePipeline(){if(!me)return;const {data,error}=await sb.from('sales_pipeline').select('*').order('updated_at',{ascending:false});if(error){setSync('Cloud unavailable — offline changes will queue','offline');return}for(const row of data||[])pipeline[row.lead_key]={stage:row.stage,notes:row.notes||'',updated:row.updated_at,contacted_at:row.contacted_at,replied_at:row.replied_at,paid_at:row.paid_at,fulfilled_at:row.fulfilled_at};cache();await flushPending();render();setSync(`Supabase synced as ${me.email}`,'ok')}
async function flushPending(){if(!me||!navigator.onLine||!pending.length)return;const remain=[];for(const item of pending){const old=pipeline[item.leadKey]||{};const row={user_id:me.id,lead_key:item.leadKey,business:item.business,stage:item.stage,notes:item.notes||'',contacted_at:old.contacted_at||null,replied_at:old.replied_at||null,paid_at:old.paid_at||null,fulfilled_at:old.fulfilled_at||null};const {data,error}=await sb.from('sales_pipeline').upsert(row,{onConflict:'user_id,lead_key'}).select().single();if(error){remain.push(item);continue}pipeline[item.leadKey]={stage:data.stage,notes:data.notes||'',updated:data.updated_at,contacted_at:data.contacted_at,replied_at:data.replied_at,paid_at:data.paid_at,fulfilled_at:data.fulfilled_at};await sb.from('sales_pipeline_audit').insert({user_id:me.id,lead_key:item.leadKey,business:item.business,from_stage:item.fromStage||null,to_stage:data.stage,notes_snapshot:data.notes||''})}pending=remain;cache()}
async function save(l,stage,notes=st(l).notes||''){const leadKey=key(l),prev=st(l),item={leadKey,business:l.business,stage,notes,fromStage:prev.stage,clientUpdatedAt:new Date().toISOString()};pipeline[leadKey]={...pipeline[leadKey],stage,notes,updated:item.clientUpdatedAt};pending=pending.filter(x=>x.leadKey!==leadKey);pending.push(item);cache();render();if(me&&navigator.onLine){setSync('Saving…','busy');await flushPending();render();setSync(pending.length?`${pending.length} offline change(s) queued`:`Supabase synced as ${me.email}`,pending.length?'warn':'ok')}else setSync(me?'Offline change queued':'Local cache only — sign in to sync',me?'offline':'warn')}
async function loadBootstrap(force=false){const b=force?`?v=${Date.now()}`:'';const[a,s]=await Promise.all([fetch(`data/leads.json${b}`,{cache:force?'no-store':'default'}),fetch(`data/scripts.json${b}`,{cache:force?'no-store':'default'})]);bootstrap=await a.json();scripts=(await s.json()).scripts;feed=bootstrap;$('#lastUpdated').textContent=`${feed.meta.lastUpdated} • ${feed.meta.sourceOfTruth}`;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
async function refreshAll(){await loadBootstrap(true);if(me)await loadPrivateMaster();await loadRemotePipeline();render()}
function cp(t){navigator.clipboard.writeText(t||'');toast('Copied')}
function toast(t){const x=document.createElement('div');x.textContent=t;x.className='toast';document.body.appendChild(x);setTimeout(()=>x.remove(),1500)}
function fact(label,value){return value?`<div class="fact"><span>${esc(label)}</span><b>${esc(value)}</b></div>`:''}
function replyBlock(label,text){return text?`<details><summary>${esc(label)}</summary><div class="pitch">${esc(text)}</div><button class="ghost copy-inline" data-copytext="${esc(text)}">Copy</button></details>`:''}
function openLead(l){const s=st(l),email=l.email?`mailto:${encodeURIComponent(l.email)}?subject=${encodeURIComponent(l.subject||'')}&body=${encodeURIComponent(l.initial||'')}`:'',generic={interested:fill(replyPlaybook.interested,l),price:fill(replyPlaybook.price,l),proof:fill(replyPlaybook.proof,l),more_info:fill(replyPlaybook.more_info,l),later:fill(replyPlaybook.later,l)};$('#leadDetail').innerHTML=`
<span class="badge">#${esc(l.rank)} • ${esc(l.tier)}</span><h2>${esc(l.business)}</h2><p class="muted">${esc(l.lead_type||'Customer Prospect')} • ${esc(l.category)} • ${esc(l.city)} • verified ${esc(l.verified)}</p>
<div class="fact-grid">${fact('Email',l.email)}${fact('Alt email',l.alternate_email)}${fact('Phone',l.phone)}${fact('Reachability',l.reachability)}${fact('Score',l.score)}${fact('Deliverability',l.deliverability_score)}</div>
<h3>Evidence / why now</h3><p>${esc(l.evidence||l.opportunity)}</p><p class="muted">${esc(l.opportunity&&l.evidence?l.opportunity:'')}</p>
<div class="actions">${email?`<a href="${email}">Email</a>`:''}${l.phone?`<a href="tel:${esc(String(l.phone).replace(/[^\d+]/g,''))}">Call</a>`:''}${l.source?`<a target="_blank" rel="noopener" href="${esc(l.source)}">Source</a>`:''}${l.website?`<a target="_blank" rel="noopener" href="${esc(l.website)}">Website</a>`:''}</div>
<h3>Initial outreach</h3><div class="pitch">${esc(l.initial||'')}</div><button id="copyPitch" class="ghost">Copy initial email</button>
<h3>Follow-up + FAQ/reply playbook</h3>${replyBlock('Follow-up 1',l.follow_up_1)}${replyBlock('Follow-up 2',l.follow_up_2)}${replyBlock('Interested / YES',l.interested_reply||generic.interested)}${replyBlock('Price question',l.price_reply||generic.price)}${replyBlock('Proof question',l.proof_reply||generic.proof)}${replyBlock('More info / what do I get?',l.more_info_reply||generic.more_info)}${replyBlock('Needs time',l.later_reply||generic.later)}${replyBlock('Bounce fallback',l.bounce_fallback)}
<h3>Prospect-specific sample</h3><div class="sample-box"><b>${esc(l.sample_headline||l.graphic_ref||'Private sample direction')}</b><p>${esc(l.sample_supporting||'')}</p><p>${esc(l.sample_visual||'')}</p><p><strong>CTA:</strong> ${esc(l.sample_cta||'')}</p>${l.graphic_ref?`<p class="muted">Graphic reference: ${esc(l.graphic_ref)}</p>`:''}</div>
<h3>Generate finished product in ChatGPT</h3><div class="pitch">${esc(l.chatgpt_prompt||productPrompt(l))}</div><button id="copyProductPrompt" class="wide-btn">Copy ChatGPT fulfillment prompt</button>
<h3>Pipeline + notes</h3><select id="stageSelect">${STAGES.map(x=>`<option ${x===s.stage?'selected':''}>${esc(x)}</option>`).join('')}</select><label class="notes-label">Notes<textarea id="leadNotes" placeholder="Record only genuine contact/reply/payment/fulfillment notes.">${esc(s.notes||'')}</textarea></label><button id="saveLead" class="wide-btn">Save pipeline + notes</button>${me?'<button id="viewAudit" class="ghost wide-btn">View audit history</button>':'<p class="muted">Sign in to persist changes across devices.</p>'}<p class="muted">Sources: ${esc(l.source_artifacts||l.source_versions||'')}</p><div id="auditBox"></div>`;
$('#copyPitch').onclick=()=>cp(l.initial||'');$('#copyProductPrompt').onclick=()=>cp(l.chatgpt_prompt||productPrompt(l));$('#saveLead').onclick=async()=>{await save(l,$('#stageSelect').value,$('#leadNotes').value);toast(me?'Saved / queued for Supabase sync':'Saved locally; sign in to sync')};if(me)$('#viewAudit').onclick=()=>showAudit(l);$$('.copy-inline').forEach(b=>b.onclick=()=>cp(b.dataset.copytext));$('#leadDialog').showModal()}
async function showAudit(l){const box=$('#auditBox');box.textContent='Loading history…';const {data,error}=await sb.from('sales_pipeline_audit').select('*').eq('lead_key',key(l)).order('changed_at',{ascending:false}).limit(50);if(error){box.textContent=error.message;return}box.innerHTML=`<h3>Audit history</h3>${(data||[]).map(a=>`<div class="audit"><b>${esc(a.from_stage||'—')} → ${esc(a.to_stage)}</b><span>${esc(new Date(a.changed_at).toLocaleString())}</span><p>${esc(a.notes_snapshot||'')}</p></div>`).join('')||'<p class="muted">No recorded changes yet.</p>'}`}
function card(l){const s=st(l);return `<article class="card"><div class="lead-top"><div><span class="badge">#${esc(l.rank)} • ${esc(l.tier)}</span><h3>${esc(l.business)}</h3></div><span class="badge">${esc(s.stage)}</span></div><p class="muted">${esc(l.lead_type||'Customer Prospect')} • ${esc(l.category)} • ${esc(l.reachability)}</p><p class="opportunity">${esc(l.opportunity||l.evidence)}</p><div class="actions"><button data-open="${esc(l.id||l.rank)}">Open</button><button data-copy="${esc(l.id||l.rank)}" class="ghost">Copy pitch</button>${l.email?`<a href="mailto:${encodeURIComponent(l.email)}?subject=${encodeURIComponent(l.subject||'')}&body=${encodeURIComponent(l.initial||'')}">Email</a>`:''}</div></article>`}
function render(){const q=($('#search')?.value||'').toLowerCase(),f=$('#filter')?.value||'all',ls=feed.leads.filter(l=>(!q||JSON.stringify(l).toLowerCase().includes(q))&&(f==='all'||l.tier===f||l.lead_type===f||st(l).stage===f));$('#leadList').innerHTML=ls.map(card).join('');$('#pipelineList').innerHTML=feed.leads.map(card).join('');const n=feed.leads.find(l=>!['Do Not Contact','Won/Paid','Fulfilled','Lost/Not a Fit'].includes(st(l).stage))||feed.leads[0];if(n){$('#nextLead').textContent=n.business;$('#nextWhy').textContent=n.opportunity||n.evidence||'';$('#openNext').onclick=()=>openLead(n)}const touched=feed.leads.filter(l=>st(l).stage!=='Contact Ready').length,replied=feed.leads.filter(l=>['Replied','Negotiating','Won/Paid','Fulfilled'].includes(st(l).stage)).length,direct=feed.leads.filter(l=>l.email).length;$('#stats').innerHTML=`<div class="stat"><strong>${feed.leads.length}</strong><span>${masterLoaded?'master records':'bootstrap leads'}</span></div><div class="stat"><strong>${direct}</strong><span>direct email</span></div><div class="stat"><strong>${touched}</strong><span>touched</span></div><div class="stat"><strong>${replied}</strong><span>replied+</span></div>`;$('#scriptList').innerHTML=scripts.map(s=>`<article class="card"><span class="badge">${esc(s.id)}</span><h3>${esc(s.stage)}</h3><p class="muted">${esc(s.when)}</p><div class="pitch">${esc(s.copy)}</div><div class="actions"><button data-script="${esc(s.id)}">Copy</button></div></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openLead(feed.leads.find(l=>String(l.id||l.rank)===b.dataset.open)));$$('[data-copy]').forEach(b=>b.onclick=()=>cp(feed.leads.find(l=>String(l.id||l.rank)===b.dataset.copy)?.initial||''));$$('[data-script]').forEach(b=>b.onclick=()=>cp(scripts.find(s=>s.id===b.dataset.script)?.copy||''));$('#accountBtn').textContent=me?'Owner ✓':'Sign in'}
function openAuth(){if(me){$('#authTitle').textContent='Signed in';$('#authHelp').textContent=`Authenticated as ${me.email}. Private master: ${masterLoaded?'loaded':'not loaded'}.`;$('#authEmail').hidden=true;$('#authPassword').hidden=true;$('#authSubmit').textContent='Sign out';$('#authSignup').hidden=true}else{$('#authTitle').textContent='Sign in';$('#authHelp').textContent='Sign in to load the private 981-record master and sync pipeline history across devices.';$('#authEmail').hidden=false;$('#authPassword').hidden=false;$('#authSubmit').textContent='Sign in';$('#authSignup').hidden=false}$('#authError').hidden=true;$('#authDialog').showModal()}
async function submitAuth(e){e.preventDefault();$('#authError').hidden=true;try{if(me){await sb.auth.signOut();me=null;masterLoaded=false;feed=bootstrap;await authState();render();$('#authDialog').close();return}const {data,error}=await sb.auth.signInWithPassword({email:$('#authEmail').value,password:$('#authPassword').value});if(error)throw error;me=data.user;$('#authPassword').value='';await loadPrivateMaster();await loadRemotePipeline();render();$('#authDialog').close()}catch(err){$('#authError').textContent=err.message;$('#authError').hidden=false}}
async function signup(){try{const {data,error}=await sb.auth.signUp({email:$('#authEmail').value,password:$('#authPassword').value});if(error)throw error;me=data.session?.user||null;$('#authHelp').textContent=me?'Account created and signed in.':'Account created. Check your email if confirmation is required.';if(me){await loadPrivateMaster();await loadRemotePipeline();render();$('#authDialog').close()}}catch(err){$('#authError').textContent=err.message;$('#authError').hidden=false}}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active')});$('#search').oninput=render;$('#filter').onchange=render;$('#refreshBtn').onclick=refreshAll;$('#forceRefresh').onclick=refreshAll;$('#closeDialog').onclick=()=>$('#leadDialog').close();$('#accountBtn').onclick=openAuth;$('#authCancel').onclick=()=>$('#authDialog').close();$('#authForm').onsubmit=submitAuth;$('#authSignup').onclick=signup;window.addEventListener('online',()=>{setSync('Back online — syncing…','busy');flushPending().then(()=>loadRemotePipeline())});window.addEventListener('offline',()=>setSync('Offline — changes will queue','offline'));sb.auth.onAuthStateChange(async(_event,session)=>{me=session?.user||null;if(me&&!masterLoaded){try{await loadPrivateMaster();await loadRemotePipeline()}catch(e){console.warn(e)}}else if(!me){masterLoaded=false;feed=bootstrap}render()});
(async()=>{await loadBootstrap();await authState();if(me){await loadPrivateMaster();await loadRemotePipeline()}render()})().catch(e=>{$('#nextLead').textContent='Could not load app';$('#nextWhy').textContent=e.message;setSync('Startup error','offline')});
