const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let feed={leads:[],meta:{}},scripts=[],pipeline=JSON.parse(localStorage.getItem('growthPipelineCache')||'{}'),pending=JSON.parse(localStorage.getItem('growthPipelinePending')||'[]'),me=null,setupRequired=false;
const STAGES=['Contact Ready','Contacted','Replied','Negotiating','Won/Paid','Fulfilled','Follow-up','Lost/Not a Fit','Do Not Contact'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=l=>String(l.id||l.business).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180);
function cache(){localStorage.setItem('growthPipelineCache',JSON.stringify(pipeline));localStorage.setItem('growthPipelinePending',JSON.stringify(pending))}
function st(l){return pipeline[key(l)]||{stage:l.status||'Contact Ready',notes:''}}
function setSync(text,state='idle'){ $('#syncStatus').textContent=text; $('#syncDot').className=`sync-dot ${state}`; $('#persistenceStatus').textContent=text }
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data.error||`Request failed (${r.status})`);e.status=r.status;throw e}return data}
async function authState(){try{const status=await api('/api/auth/status');setupRequired=!!status.setupRequired;try{me=(await api('/api/auth/me')).user;setSync(`Synced as ${me.email}`,'ok')}catch(e){me=null;setSync(setupRequired?'Create owner account to enable cloud sync':'Sign in to enable cloud sync','warn')}}catch{setSync('Offline/local cache only','offline')}}
async function loadRemotePipeline(){if(!me)return;try{const data=await api('/api/pipeline');for(const row of data.pipeline||[]){pipeline[row.lead_key]={stage:row.stage,notes:row.notes||'',updated:row.updated_at,contacted_at:row.contacted_at,replied_at:row.replied_at,paid_at:row.paid_at,fulfilled_at:row.fulfilled_at,do_not_contact_at:row.do_not_contact_at}}cache();await flushPending();render();setSync(`Synced as ${me.email}`,'ok')}catch(e){if(e.status===401){me=null;setSync('Session expired — sign in','warn')}else setSync('Cloud unavailable — offline changes will queue','offline')}}
async function flushPending(){if(!me||!navigator.onLine||!pending.length)return;const remain=[];for(const item of pending){try{const data=await api(`/api/pipeline/${encodeURIComponent(item.leadKey)}`,{method:'PUT',body:JSON.stringify(item)});const r=data.pipeline;pipeline[item.leadKey]={stage:r.stage,notes:r.notes||'',updated:r.updated_at,contacted_at:r.contacted_at,replied_at:r.replied_at,paid_at:r.paid_at,fulfilled_at:r.fulfilled_at,do_not_contact_at:r.do_not_contact_at}}catch{remain.push(item)}}pending=remain;cache()}
async function save(l,stage,notes=st(l).notes||''){const leadKey=key(l),item={leadKey,business:l.business,stage,notes,clientUpdatedAt:new Date().toISOString()};pipeline[leadKey]={...pipeline[leadKey],stage,notes,updated:item.clientUpdatedAt};pending=pending.filter(x=>x.leadKey!==leadKey);pending.push(item);cache();render();if(me&&navigator.onLine){setSync('Saving…','busy');await flushPending();render();setSync(pending.length?`${pending.length} offline change(s) queued`:`Synced as ${me.email}`,pending.length?'warn':'ok')}else setSync(me?'Offline change queued':'Local cache only — sign in to sync',me?'offline':'warn')}
async function load(force=false){const b=force?`?v=${Date.now()}`:'';const[a,s]=await Promise.all([fetch(`data/leads.json${b}`,{cache:force?'no-store':'default'}),fetch(`data/scripts.json${b}`,{cache:force?'no-store':'default'})]);feed=await a.json();scripts=(await s.json()).scripts;$('#lastUpdated').textContent=`${feed.meta.lastUpdated} • ${feed.meta.sourceOfTruth}`;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function cp(t){navigator.clipboard.writeText(t);toast('Copied')}
function toast(t){const x=document.createElement('div');x.textContent=t;x.className='toast';document.body.appendChild(x);setTimeout(()=>x.remove(),1400)}
function openLead(l){const s=st(l),email=l.email?`mailto:${encodeURIComponent(l.email)}?subject=${encodeURIComponent(l.subject||'')}&body=${encodeURIComponent(l.initial||'')}`:'';$('#leadDetail').innerHTML=`<span class="badge">#${esc(l.rank)} • Tier ${esc(l.tier)}</span><h2>${esc(l.business)}</h2><p class="muted">${esc(l.category)} • ${esc(l.city)} • verified ${esc(l.verified)}</p><h3>Why now</h3><p>${esc(l.opportunity)}</p><h3>Pitch</h3><div class="pitch">${esc(l.initial)}</div><div class="actions"><button id="copyPitch">Copy pitch</button>${email?`<a href="${email}">Email</a>`:''}${l.phone?`<a href="tel:${esc(l.phone.replace(/[^\d+]/g,''))}">Call</a>`:''}<a target="_blank" rel="noopener" href="${esc(l.source)}">Source</a></div><h3>Pipeline</h3><select id="stageSelect">${STAGES.map(x=>`<option ${x===s.stage?'selected':''}>${esc(x)}</option>`).join('')}</select><label class="notes-label">Notes<textarea id="leadNotes" placeholder="Record only genuine contact/reply/payment/fulfillment notes.">${esc(s.notes||'')}</textarea></label><button id="saveLead" class="wide-btn">Save pipeline</button>${me?'<button id="viewAudit" class="ghost wide-btn">View audit history</button>':'<p class="muted">Sign in to persist changes across devices.</p>'}<div id="auditBox"></div>`;$('#copyPitch').onclick=()=>cp(l.initial||'');$('#saveLead').onclick=async()=>{await save(l,$('#stageSelect').value,$('#leadNotes').value);toast(me?'Saved / queued for cloud sync':'Saved locally; sign in to sync')};if(me)$('#viewAudit').onclick=()=>showAudit(l);$('#leadDialog').showModal()}
async function showAudit(l){const box=$('#auditBox');box.textContent='Loading history…';try{const data=await api(`/api/pipeline/${encodeURIComponent(key(l))}/audit`);box.innerHTML=`<h3>Audit history</h3>${(data.audit||[]).map(a=>`<div class="audit"><b>${esc(a.from_stage||'—')} → ${esc(a.to_stage)}</b><span>${esc(new Date(a.changed_at).toLocaleString())}</span><p>${esc(a.notes_snapshot||'')}</p></div>`).join('')||'<p class="muted">No recorded changes yet.</p>'}`}catch(e){box.textContent=e.message}}
function card(l){const s=st(l);return `<article class="card"><div class="lead-top"><div><span class="badge">#${esc(l.rank)} • ${esc(l.tier)}</span><h3>${esc(l.business)}</h3></div><span class="badge">${esc(s.stage)}</span></div><p class="muted">${esc(l.category)} • ${esc(l.reachability)}</p><p class="opportunity">${esc(l.opportunity)}</p><div class="actions"><button data-open="${esc(l.rank)}">Open</button><button data-copy="${esc(l.rank)}" class="ghost">Copy pitch</button>${l.email?`<a href="mailto:${encodeURIComponent(l.email)}?subject=${encodeURIComponent(l.subject||'')}&body=${encodeURIComponent(l.initial||'')}">Email</a>`:''}${l.phone?`<a href="tel:${esc(l.phone.replace(/[^\d+]/g,''))}">Call</a>`:''}</div></article>`}
function render(){const q=($('#search')?.value||'').toLowerCase(),f=$('#filter')?.value||'all',ls=feed.leads.filter(l=>(!q||JSON.stringify(l).toLowerCase().includes(q))&&(f==='all'||l.tier===f||st(l).stage===f));$('#leadList').innerHTML=ls.map(card).join('');$('#pipelineList').innerHTML=feed.leads.map(card).join('');const n=feed.leads.find(l=>!['Do Not Contact','Won/Paid','Fulfilled','Lost/Not a Fit'].includes(st(l).stage))||feed.leads[0];if(n){$('#nextLead').textContent=n.business;$('#nextWhy').textContent=n.opportunity;$('#openNext').onclick=()=>openLead(n)}const touched=feed.leads.filter(l=>st(l).stage!=='Contact Ready').length,replied=feed.leads.filter(l=>['Replied','Negotiating','Won/Paid','Fulfilled'].includes(st(l).stage)).length;$('#stats').innerHTML=`<div class="stat"><strong>${feed.leads.length}</strong><span>active leads</span></div><div class="stat"><strong>${touched}</strong><span>touched</span></div><div class="stat"><strong>${replied}</strong><span>replied+</span></div>`;$('#scriptList').innerHTML=scripts.map(s=>`<article class="card"><span class="badge">${esc(s.id)}</span><h3>${esc(s.stage)}</h3><p class="muted">${esc(s.when)}</p><div class="pitch">${esc(s.copy)}</div><div class="actions"><button data-script="${esc(s.id)}">Copy</button></div></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openLead(feed.leads.find(l=>String(l.rank)===b.dataset.open)));$$('[data-copy]').forEach(b=>b.onclick=()=>cp(feed.leads.find(l=>String(l.rank)===b.dataset.copy).initial));$$('[data-script]').forEach(b=>b.onclick=()=>cp(scripts.find(s=>s.id===b.dataset.script).copy));$('#accountBtn').textContent=me?'Account ✓':'Sign in'}
function openAuth(){if(me){$('#authTitle').textContent='Signed in';$('#authHelp').textContent=`Authenticated as ${me.email}. Sign out below to end this browser session.`;$('#authEmail').hidden=true;$('#authPassword').hidden=true;$('#authSubmit').textContent='Sign out';$('#authSubmit').dataset.mode='logout'}else{$('#authTitle').textContent=setupRequired?'Create owner account':'Sign in';$('#authHelp').textContent=setupRequired?'First run: create the single owner account. Registration closes immediately afterward.':'Sign in to sync pipeline history across devices.';$('#authEmail').hidden=false;$('#authPassword').hidden=false;$('#authSubmit').textContent=setupRequired?'Create owner':'Sign in';$('#authSubmit').dataset.mode=setupRequired?'setup':'login'}$('#authError').hidden=true;$('#authDialog').showModal()}
async function submitAuth(e){e.preventDefault();const mode=$('#authSubmit').dataset.mode;$('#authError').hidden=true;try{if(mode==='logout'){await api('/api/auth/logout',{method:'POST',body:'{}'});me=null;await authState();render();$('#authDialog').close();return}const body=JSON.stringify({email:$('#authEmail').value,password:$('#authPassword').value});const data=await api(mode==='setup'?'/api/auth/setup':'/api/auth/login',{method:'POST',body});me=data.user;setupRequired=false;$('#authPassword').value='';await loadRemotePipeline();render();$('#authDialog').close()}catch(err){$('#authError').textContent=err.message;$('#authError').hidden=false}}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active')});$('#search').oninput=render;$('#filter').onchange=render;$('#refreshBtn').onclick=()=>load(true);$('#forceRefresh').onclick=()=>load(true);$('#closeDialog').onclick=()=>$('#leadDialog').close();$('#accountBtn').onclick=openAuth;$('#authCancel').onclick=()=>$('#authDialog').close();$('#authForm').onsubmit=submitAuth;window.addEventListener('online',()=>{setSync('Back online — syncing…','busy');flushPending().then(()=>loadRemotePipeline())});window.addEventListener('offline',()=>setSync('Offline — changes will queue','offline'));
(async()=>{await Promise.all([load(),authState()]);await loadRemotePipeline();render()})().catch(e=>{$('#nextLead').textContent='Could not load app';$('#nextWhy').textContent=e.message;setSync('Startup error','offline')});