'use client';
import{useEffect,useMemo,useState}from'react';
import type{User}from'@supabase/supabase-js';
import{blankBusiness,evidenceLabels,score,type BusinessDNA,type BusinessRecord,type BusinessStage}from'@/lib/fdos';
import{supabase}from'@/lib/supabase';
import{addDecision,addMemory,addOpportunity,addRisk,addValue,ensureBusiness,loadBusinessRecord,saveDNA}from'@/lib/business-store';

const stages:BusinessStage[]=['Idea','Exploring','Validating','Building','Pre-Launch','Launched','Finding Traction','Growing','Systemizing','Scaling','Portfolio','Dynasty'];
const glossary:Record<string,string>={
'Evidence':'Information that supports a claim. Founder Dynasty OS labels important claims so you can tell what is known from what is only assumed.',
'Business DNA':'The living record of what the business is: its purpose, customer, problem, offer, money model, advantages, limits and current goal.',
'Value Map':'A view of where the business creates value, captures value, loses value, has value at risk, owns useful assets, or has new opportunities.',
'Business Memory':'A dated record of important decisions, experiments, evidence, changes and lessons so the business does not have to relearn the same things.',
'Opportunity':'A possible action or change that may make the business more useful, resilient or valuable.',
'Risk':'Something that could hurt the business, reduce value, delay progress or make an important goal harder to reach.',
'CRM':'Customer Relationship Management. A system for keeping track of potential customers, conversations, follow-ups, sales and customer history.'
};
function Term({children}:{children:string}){const[open,setOpen]=useState(false);return <span className="termWrap"><button type="button" className="term" onClick={()=>setOpen(!open)} onDoubleClick={()=>setOpen(true)} aria-expanded={open}>{children}</button>{open&&<span className="termBubble" role="tooltip"><b>{children}</b>{glossary[children]}<button type="button" onClick={()=>setOpen(false)} aria-label="Close definition">×</button></span>}</span>}
function Field({label,value,onChange,wide=false}:{label:string;value:string;onChange:(v:string)=>void;wide?:boolean}){return <label className={wide?'wide':''}>{label}<textarea value={value} onChange={e=>onChange(e.target.value)} /></label>}

export default function Home(){
 const[user,setUser]=useState<User|null>(null);const[record,setRecord]=useState<BusinessRecord>(blankBusiness);const[editing,setEditing]=useState(false);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authMode,setAuthMode]=useState<'signin'|'signup'>('signin');const[status,setStatus]=useState('Checking your workspace…');const[websiteUrl,setWebsiteUrl]=useState('');const[evidenceResult,setEvidenceResult]=useState<any>(null);const[busy,setBusy]=useState(false);
 const ranked=useMemo(()=>[...record.opportunities].sort((a,b)=>score(b)-score(a)),[record.opportunities]);
 const highRisks=record.risks.filter(r=>r.level==='High').length;const openDecisions=record.decisions.filter(d=>d.status==='Open').length;
 const updateDNA=(key:keyof BusinessDNA,value:string)=>setRecord(r=>({...r,dna:{...r.dna,[key]:value}}));

 async function hydrate(u:User){setStatus('Loading your business record…');try{const id=await ensureBusiness(u);const loaded=await loadBusinessRecord(u,id);setRecord(loaded);setStatus('Cloud sync ready.');}catch(e:any){setStatus(`Cloud sync error: ${e.message}`)}}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user||null);if(data.user)hydrate(data.user);else setStatus('Sign in to save this business across devices.');});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);if(session?.user)hydrate(session.user);else{setRecord(blankBusiness);setStatus('Signed out.');}});return()=>data.subscription.unsubscribe();},[]);

 async function auth(e:React.FormEvent){e.preventDefault();setBusy(true);setStatus(authMode==='signin'?'Signing in…':'Creating account…');try{const result=authMode==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session)setStatus('Account created. Check your email if confirmation is required.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function signOut(){setBusy(true);const{error}=await supabase.auth.signOut();setBusy(false);if(error)setStatus(error.message)}
 async function persistDNA(next=record.dna){if(!user||!record.businessId)return;setBusy(true);try{await saveDNA(user,record.businessId,next);setStatus('Business DNA saved to the cloud.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function changeStage(stage:BusinessStage){const dna={...record.dna,stage};setRecord(r=>({...r,dna}));if(user&&record.businessId){try{await saveDNA(user,record.businessId,dna);await addMemory(user,record.businessId,{kind:'Business stage changed',summary:`Business stage changed to ${stage}.`,evidence:'E4'});await hydrate(user);}catch(e:any){setStatus(e.message)}}}
 async function reload(){if(user&&record.businessId){const loaded=await loadBusinessRecord(user,record.businessId);setRecord(loaded)}}
 async function quickAdd(kind:'value'|'decision'|'risk'|'opportunity'|'memory'){
   if(!user||!record.businessId){setStatus('Sign in before saving business records.');return}
   try{
    if(kind==='value'){const title=prompt('Value item title');if(!title)return;const detail=prompt('What is happening?')||'';await addValue(user,record.businessId,{kind:'Opportunity',title,detail,evidence:'E4'});}
    if(kind==='decision'){const question=prompt('What decision needs to be made?');if(!question)return;const next=prompt('What is the next useful step?')||'';await addDecision(user,record.businessId,{question,status:'Open',next,evidence:'E4'});}
    if(kind==='risk'){const title=prompt('Risk title');if(!title)return;const response=prompt('How should the business respond?')||'';await addRisk(user,record.businessId,{title,level:'Medium',response,evidence:'E4'});}
    if(kind==='opportunity'){const title=prompt('Opportunity title');if(!title)return;const observation=prompt('Why might this matter?')||'';await addOpportunity(user,record.businessId,{title,observation,evidence:'E4',confidence:50,impact:5,speed:5,reversibility:5,cost:5,complexity:5,risk:5});}
    if(kind==='memory'){const summary=prompt('What happened or what did you learn?');if(!summary)return;await addMemory(user,record.businessId,{kind:'Founder note',summary,evidence:'E4'});}
    await reload();setStatus('Saved.');
   }catch(e:any){setStatus(e.message)}
 }
 async function captureWebsiteEvidence(e:React.FormEvent){e.preventDefault();if(!user||!record.businessId)return;setBusy(true);setEvidenceResult(null);setStatus('Checking the website and capturing external evidence…');try{const{data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/evidence/website',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({businessId:record.businessId,url:websiteUrl})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not capture evidence.');setEvidenceResult(body.evidence);setStatus('External website evidence captured as E2.');await reload();}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}

 return <main>
  <header className="topbar"><div><p className="eyebrow">SMARTPICKSHOP HOLDINGS</p><strong>Founder Dynasty OS 10.0</strong></div><nav><a href="#command">Command Center</a><a href="#dna">Business DNA</a><a href="#value">Value Map</a><a href="#decisions">Decisions</a><a href="#memory">Memory</a><a href="#evidence">Evidence</a><a href="#sales">Sales</a></nav></header>

  {!user?<section className="panel authPanel"><div><p className="eyebrow">YOUR PRIVATE BUSINESS WORKSPACE</p><h2>Sign in to keep one business record across devices.</h2><p className="plainIntro">Each signed-in user gets their own cloud-backed Founder Dynasty OS workspace. Your Business DNA, Value Map, Decisions, Risks, Opportunities and Business Memory are stored under that same business record.</p></div><form className="authForm" onSubmit={auth}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{authMode==='signin'?'Sign in':'Create account'}</button><button type="button" className="ghostButton" onClick={()=>setAuthMode(authMode==='signin'?'signup':'signin')}>{authMode==='signin'?'Need an account? Create one':'Already have an account? Sign in'}</button></form></section>:<section className="syncBar"><span><b>{user.email}</b> · {status}</span><button onClick={signOut} disabled={busy}>Sign out</button></section>}

  <section className="hero" id="command"><div><p className="eyebrow">THE OPERATING INTELLIGENCE OF THE BUSINESS</p><h1>Run the whole business. <span>Not just the sales part.</span></h1><p className="lede">One authenticated business record now connects what the business is, what it knows, what could create value, what could go wrong, what decisions matter, and what happened before.</p><p className="helpHint">Underlined terms explain themselves when tapped. Humanity has produced enough jargon already.</p></div><div className="stageBadge"><small>CURRENT BUSINESS STAGE</small><b>{record.dna.stage}</b><span>{record.dna.name}</span></div></section>

  <section className="commandGrid"><article className="focusCard"><p className="eyebrow">WHAT MATTERS MOST NOW?</p><h2>{record.dna.currentGoal||'Define the next useful goal.'}</h2><p>Why: the business is currently in <b>{record.dna.stage}</b> stage. The OS should prioritize the largest useful uncertainty or value opportunity at this stage.</p><button onClick={()=>document.getElementById('opportunities')?.scrollIntoView({behavior:'smooth'})}>See the best next actions</button></article><div className="signalGrid"><article><b>{openDecisions}</b><span>open decisions</span></article><article><b>{highRisks}</b><span>high risks</span></article><article><b>{record.opportunities.length}</b><span>saved opportunities</span></article><article><b>{record.memory.length}</b><span>memory entries</span></article></div></section>

  <section className="panel" id="dna"><div className="panelHead"><div><p className="eyebrow">SHARED BUSINESS RECORD</p><h2><Term>Business DNA</Term></h2><p className="plainIntro">Every major module reads from this same business record. Edit it once, save it once, and it follows the signed-in account.</p></div><div className="buttonRow"><button className="smallButton" onClick={()=>setEditing(!editing)}>{editing?'Done editing':'Edit Business DNA'}</button>{user&&<button className="smallButton" onClick={()=>persistDNA()} disabled={busy}>Save to cloud</button>}</div></div>
   <div className="stageRail">{stages.map(s=><button key={s} className={record.dna.stage===s?'active':''} onClick={()=>changeStage(s)}>{s}</button>)}</div>
   {editing?<div className="dnaForm"><label>Business / idea name<input value={record.dna.name} onChange={e=>updateDNA('name',e.target.value)}/></label><Field label="Purpose" value={record.dna.purpose} onChange={v=>updateDNA('purpose',v)}/><Field label="Problem we think exists" value={record.dna.problem} onChange={v=>updateDNA('problem',v)}/><Field label="Customer / user" value={record.dna.customer} onChange={v=>updateDNA('customer',v)}/><Field label="Offer / solution" value={record.dna.offer} onChange={v=>updateDNA('offer',v)}/><Field label="How it may make money" value={record.dna.revenueModel} onChange={v=>updateDNA('revenueModel',v)}/><Field label="Possible advantage" value={record.dna.advantage} onChange={v=>updateDNA('advantage',v)}/><Field label="Main constraint" value={record.dna.constraint} onChange={v=>updateDNA('constraint',v)}/><Field label="Current goal" value={record.dna.currentGoal} onChange={v=>updateDNA('currentGoal',v)} wide/></div>:<div className="dnaGrid">{[['Purpose',record.dna.purpose],['Problem',record.dna.problem],['Customer',record.dna.customer],['Offer',record.dna.offer],['Money model',record.dna.revenueModel],['Advantage',record.dna.advantage],['Constraint',record.dna.constraint],['Current goal',record.dna.currentGoal]].map(([k,v])=><article key={k}><small>{k}</small><p>{v||'Not defined yet.'}</p></article>)}</div>}
  </section>

  <section className="panel" id="value"><div className="panelHead"><div><p className="eyebrow">WHERE VALUE LIVES OR LEAKS</p><h2><Term>Value Map</Term></h2></div>{user&&<button className="smallButton" onClick={()=>quickAdd('value')}>Add value item</button>}</div><div className="valueGrid">{record.valueMap.length?record.valueMap.map(v=><article key={v.id}><span className={'kind '+v.kind.replace(' ','').toLowerCase()}>{v.kind}</span><h3>{v.title}</h3><p>{v.detail}</p><small>{v.evidence} · {evidenceLabels[v.evidence]}</small></article>):<p className="empty">No saved value items yet.</p>}</div></section>

  <section className="two" id="opportunities"><div className="panel"><div className="panelHead"><div><p className="eyebrow">OPPORTUNITY ENGINE</p><h2>Best next actions</h2></div>{user&&<button className="smallButton" onClick={()=>quickAdd('opportunity')}>Add opportunity</button>}</div><p className="plainIntro">An <Term>Opportunity</Term> is saved against this business record and ranked using likely value, speed, cost, complexity, risk and reversibility.</p><div className="stack">{ranked.length?ranked.map(o=><article className="op" key={o.id}><div><span className="evidence">{o.evidence} · {evidenceLabels[o.evidence]}</span><h3>{o.title}</h3><p>{o.observation}</p></div><strong title="Priority score">{score(o)}</strong></article>):<p className="empty">No saved opportunities yet.</p>}</div></div>
   <div className="panel"><div className="panelHead"><div><p className="eyebrow">RISK CENTER</p><h2>What could hurt us?</h2></div>{user&&<button className="smallButton" onClick={()=>quickAdd('risk')}>Add risk</button>}</div><div className="stack">{record.risks.length?record.risks.map(r=><article className="miniCard" key={r.id}><div className="miniHead"><b>{r.title}</b><span className={'risk '+r.level.toLowerCase()}>{r.level}</span></div><p>{r.response}</p><small>{r.evidence} · {evidenceLabels[r.evidence]}</small></article>):<p className="empty">No saved risks yet.</p>}</div></div></section>

  <section className="panel" id="decisions"><div className="panelHead"><div><p className="eyebrow">DECISION ENGINE</p><h2>Important choices that should not vanish into chat history</h2></div>{user&&<button className="smallButton" onClick={()=>quickAdd('decision')}>Add decision</button>}</div><div className="decisionGrid">{record.decisions.length?record.decisions.map(d=><article key={d.id}><span className="tag">{d.status}</span><h3>{d.question}</h3><p><b>Next:</b> {d.next}</p><small>{d.evidence} · {evidenceLabels[d.evidence]}</small></article>):<p className="empty">No saved decisions yet.</p>}</div></section>

  <section className="panel" id="memory"><div className="panelHead"><div><p className="eyebrow">BUSINESS MEMORY</p><h2><Term>Business Memory</Term></h2></div>{user&&<button className="smallButton" onClick={()=>quickAdd('memory')}>Add memory</button>}</div><p className="plainIntro">A persistent timeline of what changed, what was learned, and what evidence supported it.</p><div className="timeline">{record.memory.length?record.memory.map(m=><article key={m.id}><time>{m.date}</time><div><b>{m.kind}</b><p>{m.summary}</p><small>{m.evidence} · {evidenceLabels[m.evidence]}</small></div></article>):<p className="empty">No memory entries yet.</p>}</div></section>

  <section className="panel" id="evidence"><div className="panelHead"><div><p className="eyebrow">FIRST REAL EVIDENCE CONNECTOR</p><h2>Capture what your public website actually says</h2><p className="plainIntro">Enter a public website URL. Founder Dynasty OS fetches the page on the server, records its title and description as E2 Current External Evidence, and adds the capture to Business Memory. It does not silently convert that evidence into a customer claim, revenue result, or proven strategy.</p></div><span className="tag">E2 · CURRENT EXTERNAL EVIDENCE</span></div>{user?<form className="evidenceForm" onSubmit={captureWebsiteEvidence}><label>Public website URL<input type="url" required placeholder="https://example.com" value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)}/></label><button disabled={busy}>Capture website evidence</button></form>:<p className="notice">Sign in before attaching external evidence to a private business record.</p>}{evidenceResult&&<article className="evidenceResult"><b>{evidenceResult.title}</b><p>{evidenceResult.summary||'No meta description was found.'}</p><small>{evidenceResult.evidenceClass} · {evidenceResult.url}</small></article>}</section>

  <section className="panel neighborhood" id="sales"><div><p className="eyebrow">CUSTOMERS & GROWTH → SALES</p><h2>Same-Day Customer Growth Pack / Sales OS</h2><p>The Sales OS remains a major connected system for prospect research, outreach, follow-up and <Term>CRM</Term> history. It belongs here, inside Customers & Growth. It does not define the rest of Founder Dynasty OS.</p></div><a className="moduleLink" href="/sales-engine-app/">Open Sales OS →</a></section>

  <section className="panel"><p className="eyebrow">HOW SURE ARE WE?</p><h2>Evidence labels</h2><div className="vault">{Object.entries(evidenceLabels).map(([k,v])=><div key={k}><b>{k}</b><span>{v}</span></div>)}</div></section>
  <footer>Founder Dynasty OS 10.0 · A SMARTPICKSHOP HOLDINGS PRODUCT · Authenticated shared business record</footer>
 </main>
}
