'use client';
import{useMemo,useState}from'react';import{demo,evidenceLabels,score,type Opportunity}from'@/lib/fdos';

const glossary:Record<string,string>={
  'Evidence':'Information that supports a claim. In Founder Dynasty OS, important claims are labeled so you can tell what is known from what is only an idea.',
  'Evidence class':'A simple label showing what kind of proof or uncertainty is behind a statement.',
  'Value Leak':'A place where a business may be losing money, customers, time, attention, or opportunity.',
  'Value Sprint':'A short test: pick one problem, take one useful action, measure what happened, then decide what to do next.',
  'KPI':'Key Performance Indicator. In plain English: the number or result you use to tell whether an action worked.',
  'Hypothesis':'An educated idea that still needs to be tested. It is not a proven fact.',
  'CRM':'Customer Relationship Management. A system for keeping track of potential customers, conversations, follow-ups, sales, and customer history.',
  'Pipeline':'The step-by-step path a potential customer moves through, such as Ready to Contact → Contacted → Replied → Paid.',
  'Audit trail':'A dated history showing what changed, when it changed, and what was recorded.',
  'Supabase':'The cloud database and account system used by parts of Founder Dynasty OS to securely save information across devices.',
  'PWA':'Progressive Web App. A website designed to behave more like an installable phone or computer app.',
  'RLS':'Row Level Security. Database rules that help make sure one signed-in user cannot read another user’s private records.',
  'Forecast':'A best estimate about what may happen later. A forecast is not a guarantee.',
  'Financial model assumption':'A number or belief used to calculate a possible financial outcome. It must not be presented as actual money earned.',
  'External evidence':'Information checked against a source outside Founder Dynasty OS.',
  'Customer-derived evidence':'Something a real customer or potential customer actually did or said, such as replying to an email.',
  'Opportunity ranking':'Putting possible actions in priority order so you know what deserves attention first.',
  'KEEP / REVISE / REVERT':'After a test: KEEP what worked, REVISE what needs improvement, or REVERT by undoing a harmful change.'
};
function Term({children}:{children:string}){const[open,setOpen]=useState(false);return <span className="termWrap"><button type="button" className="term" onClick={()=>setOpen(!open)} onDoubleClick={()=>setOpen(true)} aria-expanded={open}>{children}</button>{open&&<span className="termBubble" role="tooltip"><b>{children}</b>{glossary[children]}<button type="button" onClick={()=>setOpen(false)} aria-label="Close definition">×</button></span>}</span>}
export default function Home(){const[website,setWebsite]=useState('');const[facebook,setFacebook]=useState('');const[idea,setIdea]=useState('');const[scanned,setScanned]=useState(false);const ranked=useMemo(()=>[...demo].sort((a,b)=>score(b)-score(a)),[]);function runScan(e:React.FormEvent){e.preventDefault();setScanned(true)}return <main>
<header className="hero"><div><p className="eyebrow">SMARTPICKSHOP HOLDINGS · FOUNDER DYNASTY OS 10.0</p><h1>Know what to do next. <span>Know why.</span></h1><p className="lede">Founder Dynasty OS helps turn a messy business idea into a short list of useful actions. It separates what we know from what we are only testing, keeps a record of what actually happened, and helps you decide what to do next.</p><p className="helpHint">Underlined business or technical words are explainable. Tap them for a plain-English definition. The full glossary is at the bottom.</p></div><div className="status">PROOF CHECKING IS ON</div></header>
<section className="grid metrics"><article><b>8</b><small>ways we label proof</small></article><article><b>1</b><small>best next action at a time</small></article><article><b>0</b><small>made-up results allowed</small></article><article><b>∞</b><small>ideas you can test</small></article></section>
<section className="panel"><div className="panelHead"><div><p className="eyebrow">FIND WHERE THE BUSINESS MAY BE LOSING VALUE</p><h2>What are you working on?</h2></div><span className="tag">PREVIEW · NOT A REAL WEB SEARCH</span></div><p className="plainIntro">Give the system a website, business page, or description. The goal is to find possible <Term>Value Leak</Term>s — places where money, customers, time, or opportunity may be slipping away.</p><form onSubmit={runScan} className="form"><label>Business website<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://yourbusiness.com"/></label><label>Facebook or other business page<input value={facebook} onChange={e=>setFacebook(e.target.value)} placeholder="Optional"/></label><label className="wide">Tell us about the business or problem<textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Example: I get website visitors but very few ask for an estimate."/></label><button>Find possible next actions</button></form>{scanned&&<p className="notice"><b>Important:</b> This preview did not actually visit the links you entered. The ideas below are examples until they are checked against real information.</p>}</section>
<section className="two"><div className="panel"><p className="eyebrow">WHAT SHOULD I DO FIRST?</p><h2>Best next actions</h2><p className="plainIntro"><Term>Opportunity ranking</Term> means putting possible actions in order so the most useful one is easier to spot.</p><div className="stack">{ranked.map((o:Opportunity)=><article className="op" key={o.id}><div><span className="evidence">{o.evidence} · {evidenceLabels[o.evidence]}</span><h3>{o.title}</h3><p>{o.observation}</p></div><strong title="Priority score">{score(o)}</strong></article>)}</div></div>
<div className="panel"><p className="eyebrow">TEST ONE THING AT A TIME</p><h2>Run one short business test</h2><p className="plainIntro">We call this a <Term>Value Sprint</Term>. You do something useful, measure what really happened, and learn from it.</p><ol className="sprint"><li>1. Pick the problem <span>Choose one important problem instead of trying to fix everything.</span></li><li>2. Check the proof <span>Separate facts from a <Term>Hypothesis</Term> that still needs testing.</span></li><li>3. Take one action <span>Do one specific thing that could improve the situation.</span></li><li>4. Measure the result <span>Choose a <Term>KPI</Term>: a number or result that tells you whether it helped.</span></li><li>5. Decide <span><Term>KEEP / REVISE / REVERT</Term>.</span></li></ol></div></section>
<section className="panel"><p className="eyebrow">HOW SURE ARE WE?</p><h2>Proof labels</h2><p className="plainIntro">Every important claim should have an <Term>Evidence class</Term>. These labels stop guesses, examples and forecasts from quietly turning into “facts.”</p><div className="vault">{Object.entries(evidenceLabels).map(([k,v])=><div key={k}><b>{k}</b><span>{v}</span></div>)}</div></section>
<section className="panel glossary" id="glossary"><p className="eyebrow">PLAIN-ENGLISH GLOSSARY</p><h2>What do these words mean?</h2><p className="plainIntro">This is the master help section for business and technical terms used throughout Founder Dynasty OS. The same definitions can appear beside a term when you tap it.</p><div className="glossaryGrid">{Object.entries(glossary).sort(([a],[b])=>a.localeCompare(b)).map(([term,definition])=><article key={term}><h3>{term}</h3><p>{definition}</p></article>)}</div></section>
<footer>Founder Dynasty OS 10.0 · SMARTPICKSHOP HOLDINGS · Built to explain the business, not make you learn computer jargon first.</footer></main>}
