'use client';
import{useEffect,useMemo,useState}from'react';
import type{User}from'@supabase/supabase-js';
import{blankBusiness,evidenceLabels,score,type BusinessDNA,type BusinessRecord,type BusinessStage,type EvidenceProposal}from'@/lib/fdos';
import{supabase}from'@/lib/supabase';
import{addDecision,addMemory,addOpportunity,addRisk,addValue,approveEvidenceProposal,ensureBusiness,loadBusinessRecord,loadEvidenceProposals,rejectEvidenceProposal,saveDNA}from'@/lib/business-store';

const stages:BusinessStage[]=['Idea','Exploring','Validating','Building','Pre-Launch','Launched','Finding Traction','Growing','Systemizing','Scaling','Portfolio','Dynasty'];
const glossary:Record<string,string>={'Evidence':'Information that supports a claim. Founder Dynasty OS labels important claims so you can tell what is known from what is assumed.','Business DNA':'The living record of what the business is: purpose, customer, problem, offer, money model, advantage, limits and current goal.','Value Map':'Where the business creates, captures, loses, risks, or owns value.','Business Memory':'A dated record of decisions, evidence, changes and lessons.','Opportunity':'A possible action or change that may make the business more useful, resilient or valuable.','Risk':'Something that could hurt the business or make an important goal harder to reach.','CRM':'Customer Relationship Management. A system for keeping track of possible and existing customers.'};
function Term({children}:{children:string}){const[open,setOpen]=useState(false);return <span className="termWrap"><button type="button" className="term" onClick={()=>setOpen(!open)} aria-expanded={open}>{children}</button>{open&&<span className="termBubble" role="tooltip"><b>{children}</b>{glossary[children]}<button type="button" onClick={()=>setOpen(false)} aria-label="Close definition">×</button></span>}</span>}
function Field({label,value,onChange,wide=false}:{label:string;value:string;onChange:(v:string)=>void;wide?:boolean}){return <label className={wide?'wide':''}>{label}<textarea value={value} onChange={e=>onChange(e.target.value)}/></label>}
function SourceLink({url}:{url?:string}){return url?<a className="sourceLink" href={url} target="_blank" rel="noreferrer">View supporting source ↗</a>:null}
type ComposerKind='value'|'decision'|'risk'|'opportunity'|'memory';
type ComposerState={kind:ComposerKind;title:string;detail:string;secondary:string;category:string}|null;

export default function Home(){
 const[user,setUser]=useState<User|null>(null);const[record,setRecord]=useState<BusinessRecord>(blankBusiness);const[editing,setEditing]=useState(false);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authMode,setAuthMode]=useState<'signin'|'signup'>('signin');const[status,setStatus]=useState('Checking your workspace…');const[websiteUrl,setWebsiteUrl]=useState('');const[evidenceResult,setEvidenceResult]=useState<any>(null);const[proposals,setProposals]=useState<EvidenceProposal[]>([]);const[composer,setComposer]=useState<ComposerState>(null);const[busy,setBusy]=useState(false);
 const ranked=useMemo(()=>[...record.opportunities].sort((a,b)=>score(b)-score(a)),[record.opportunities]);const highRisks=record.risks.filter(r=>r.level==='High').length;const openDecisions=record.decisions.filter(d=>d.status==='Open').length;
 const updateDNA=(key:keyof BusinessDNA,value:string)=>setRecord(r=>({...r,dna:{...r.dna,[key]:value}}));
 async function hydrate(u:User){setStatus('Loading your business record…');try{const id=await ensureBusiness(u);const[loaded,p]=await Promise.all([loadBusinessRecord(u,id),loadEvidenceProposals(u,id)]);setRecord(loaded);setProposals(p);setStatus('Cloud sync ready.');}catch(e:any){setStatus(`Cloud sync error: ${e.message}`)}}
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user||null);if(data.user)hydrate(data.user);else setStatus('Sign in to save this business across devices.');});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);if(session?.user)hydrate(session.user);else{setRecord(blankBusiness);setProposals([]);setStatus('Signed out.');}});return()=>data.subscription.unsubscribe();},[]);
 async function auth(e:React.FormEvent){e.preventDefault();setBusy(true);setStatus(authMode==='signin'?'Signing in…':'Creating account…');try{const result=authMode==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session)setStatus('Account created. Check your email if confirmation is required.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function signOut(){setBusy(true);const{error}=await supabase.auth.signOut();setBusy(false);if(error)setStatus(error.message)}
 async function persistDNA(next=record.dna){if(!user||!record.businessId)return;setBusy(true);try{await saveDNA(user,record.businessId,next);await addMemory(user,record.businessId,{kind:'Business DNA updated',summary:'Founder approved changes to the shared Business DNA record.',evidence:'E4'});await hydrate(user);setStatus('Business DNA saved.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function changeStage(stage:BusinessStage){const dna={...record.dna,stage};setRecord(r=>({...r,dna}));if(user&&record.businessId){try{await saveDNA(user,record.businessId,dna);await addMemory(user,record.businessId,{kind:'Business stage changed',summary:`Business stage changed to ${stage}.`,evidence:'E4'});await hydrate(user);}catch(e:any){setStatus(e.message)}}}
 function openComposer(kind:ComposerKind){const defaults:Record<ComposerKind,ComposerState>={value:{kind,title:'',detail:'',secondary:'',category:'Opportunity'},decision:{kind,title:'',detail:'',secondary:'',category:'Open'},risk:{kind,title:'',detail:'',secondary:'',category:'Medium'},opportunity:{kind,title:'',detail:'',secondary:'',category:'55'},memory:{kind,title:'Founder note',detail:'',secondary:'',category:'E4'}};setComposer(defaults[kind]);}
 async function saveComposer(e:React.FormEvent){e.preventDefault();if(!composer||!user||!record.businessId)return;setBusy(true);try{if(composer.kind==='value')await addValue(user,record.businessId,{kind:composer.category as any,title:composer.title,detail:composer.detail,evidence:'E4'});if(composer.kind==='decision')await addDecision(user,record.businessId,{question:composer.title,status:'Open',next:composer.detail,evidence:'E4'});if(composer.kind==='risk')await addRisk(user,record.businessId,{title:composer.title,level:composer.category as any,response:composer.detail,evidence:'E4'});if(composer.kind==='opportunity')await addOpportunity(user,record.businessId,{title:composer.title,observation:composer.detail,evidence:'E4',confidence:Number(composer.category)||55,impact:6,speed:6,reversibility:7,cost:4,complexity:4,risk:3});if(composer.kind==='memory')await addMemory(user,record.businessId,{kind:composer.title||'Founder note',summary:composer.detail,evidence:'E4'});setComposer(null);await hydrate(user);setStatus('Saved to the shared business record.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function captureWebsiteEvidence(e:React.FormEvent){e.preventDefault();if(!user||!record.businessId)return;setBusy(true);setEvidenceResult(null);setStatus('Checking the website and capturing external evidence…');try{const{data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/evidence/website',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify({businessId:record.businessId,url:websiteUrl})});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not capture evidence.');setEvidenceResult(body.evidence);setStatus(`Captured E2 evidence and created ${body.proposals?.length||0} proposals for your review.`);await hydrate(user);}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 async function reviewProposal(p:EvidenceProposal,approve:boolean){if(!user)return;setBusy(true);try{if(approve)await approveEvidenceProposal(p.id);else await rejectEvidenceProposal(user,p.id);await hydrate(user);setStatus(approve?'Proposal approved and applied.':'Proposal rejected. Nothing was changed.');}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 const pending=proposals.filter(p=>p.status==='pending');
 return <main>
  <header className="topbar"><div><p className="eyebrow">SMARTPICKSHOP HOLDINGS</p><strong>Founder Dynasty OS 10.0</strong></div><nav><a href="#command">Command Center</a><a href="#dna">Business DNA</a><a href="#value">Value</a><a href="#decisions">Decisions</a><a href="#memory">Memory</a><a href="#evidence">Evidence</a><a href="#sales">Sales</a></nav></header>
  {!user?<section className="panel authPanel"><div><p className="eyebrow">YOUR PRIVATE BUSINESS WORKSPACE</p><h2>Sign in to keep one business record across devices.</h2><p className="plainIntro">Business DNA, value, decisions, risks, opportunities, evidence and memory all stay attached to the same account-owned business record.</p></div><form className="authForm" onSubmit={auth}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{authMode==='signin'?'Sign in':'Create account'}</button><button type="button" className="ghostButton" onClick={()=>setAuthMode(authMode==='signin'?'signup':'signin')}>{authMode==='signin'?'Need an account? Create one':'Already have an account? Sign in'}</button></form></section>:<section className="syncBar"><span><b>{user.email}</b> · {status}</span><button onClick={signOut} disabled={busy}>Sign out</button></section>}
  <section className="hero" id="command"><div><p className="eyebrow">THE OPERATING INTELLIGENCE OF THE BUSINESS</p><h1>Run the whole business. <span>Keep the evidence attached.</span></h1><p className="lede">Founder Dynasty OS now separates what a source actually says from what the system thinks you might do about it. Evidence can suggest changes, but nothing important is applied without founder approval.</p></div><div className="stageBadge"><small>CURRENT BUSINESS STAGE</small><b>{record.dna.stage}</b><span>{record.dna.name}</span></div></section>
  <section className="commandGrid"><article className="focusCard"><p className="eyebrow">WHAT MATTERS MOST NOW?</p><h2>{record.dna.currentGoal||'Define the next useful goal.'}</h2><p>The OS uses the shared record, current stage, saved risks, open decisions and evidence review queue to keep attention on the next useful move.</p><button onClick={()=>document.getElementById('opportunities')?.scrollIntoView({behavior:'smooth'})}>See next actions</button></article><div className="signalGrid"><article><b>{openDecisions}</b><span>open decisions</span></article><article><b>{highRisks}</b><span>high risks</span></article><article><b>{pending.length}</b><span>evidence proposals waiting</span></article><article><b>{record.memory.length}</b><span>memory entries</span></article></div></section>
  <section className="panel" id="dna"><div className="panelHead"><div><p className="eyebrow">SHARED BUSINESS RECORD</p><h2><Term>Business DNA</Term></h2><p className="plainIntro">This is the current working model of the business. Evidence may propose edits, but the founder decides whether they become canonical.</p></div><div className="buttonRow"><button className="smallButton" onClick={()=>setEditing(!editing)}>{editing?'Done editing':'Edit Business DNA'}</button>{user&&<button className="smallButton" onClick={()=>persistDNA()} disabled={busy}>Save approved edits</button>}</div></div><div className="stageRail">{stages.map(s=><button key={s} className={record.dna.stage===s?'active':''} onClick={()=>changeStage(s)}>{s}</button>)}</div>{editing?<div className="dnaForm"><label>Business / idea name<input value={record.dna.name} onChange={e=>updateDNA('name',e.target.value)}/></label><Field label="Why this business exists" value={record.dna.purpose} onChange={v=>updateDNA('purpose',v)}/><Field label="Problem it is trying to solve" value={record.dna.problem} onChange={v=>updateDNA('problem',v)}/><Field label="Who it is for" value={record.dna.customer} onChange={v=>updateDNA('customer',v)}/><Field label="What it offers" value={record.dna.offer} onChange={v=>updateDNA('offer',v)}/><Field label="How it may make money" value={record.dna.revenueModel} onChange={v=>updateDNA('revenueModel',v)}/><Field label="Possible advantage" value={record.dna.advantage} onChange={v=>updateDNA('advantage',v)}/><Field label="Main limit or constraint" value={record.dna.constraint} onChange={v=>updateDNA('constraint',v)}/><Field label="Most important current goal" value={record.dna.currentGoal} onChange={v=>updateDNA('currentGoal',v)} wide/></div>:<div className="dnaGrid">{[['Purpose',record.dna.purpose],['Problem',record.dna.problem],['Customer',record.dna.customer],['Offer',record.dna.offer],['Money model',record.dna.revenueModel],['Advantage',record.dna.advantage],['Constraint',record.dna.constraint],['Current goal',record.dna.currentGoal]].map(([k,v])=><article key={k}><small>{k}</small><p>{v||'Not defined yet.'}</p></article>)}</div>}</section>
  <section className="panel" id="evidence"><div className="panelHead"><div><p className="eyebrow">REAL EVIDENCE → REVIEWABLE CHANGES</p><h2>Evidence inbox</h2><p className="plainIntro">Capture a public webpage. The source is stored as E2. Founder Dynasty OS then proposes useful follow-up items. Direct observations stay E2; interpretations are labeled E5 hypotheses.</p></div></div>{user?<form className="evidenceForm" onSubmit={captureWebsiteEvidence}><label>Public webpage to examine<input type="url" placeholder="https://example.com" required value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)}/></label><button disabled={busy}>Capture website evidence</button></form>:<p className="empty">Sign in to capture evidence.</p>}{evidenceResult&&<article className="evidenceReceipt"><span className="evidence">E2 · Current External Evidence</span><h3>{evidenceResult.title}</h3><p>{evidenceResult.summary}</p><SourceLink url={evidenceResult.url}/></article>}<div className="proposalHead"><div><p className="eyebrow">FOUNDER APPROVAL QUEUE</p><h3>{pending.length?`${pending.length} proposed changes need a decision`:'No proposals waiting'}</h3></div></div><div className="proposalGrid">{pending.map(p=><article className="proposalCard" key={p.id}><div className="proposalTop"><span className="targetTag">{p.targetType==='dna'?'Business DNA':p.targetType}</span><span className="evidence">Source: E2</span></div><h3>{p.title}</h3><p>{p.rationale}</p><div className="proposalPreview"><b>What would change</b><pre>{JSON.stringify(p.payload,null,2)}</pre></div><SourceLink url={p.sourceUrl}/><div className="reviewButtons"><button disabled={busy} onClick={()=>reviewProposal(p,true)}>Approve and apply</button><button className="rejectButton" disabled={busy} onClick={()=>reviewProposal(p,false)}>Reject</button></div></article>)}</div></section>
  <section className="panel" id="value"><div className="panelHead"><div><p className="eyebrow">WHERE VALUE LIVES OR LEAKS</p><h2><Term>Value Map</Term></h2></div>{user&&<button className="smallButton" onClick={()=>openComposer('value')}>Add value item</button>}</div><div className="valueGrid">{record.valueMap.length?record.valueMap.map(v=><article key={v.id}><span className={'kind '+v.kind.replace(' ','').toLowerCase()}>{v.kind}</span><h3>{v.title}</h3><p>{v.detail}</p><small>{v.evidence} · {evidenceLabels[v.evidence]}</small><SourceLink url={v.sourceUrl}/></article>):<p className="empty">No saved value items yet.</p>}</div></section>
  <section className="two" id="opportunities"><div className="panel"><div className="panelHead"><div><p className="eyebrow">OPPORTUNITY ENGINE</p><h2>Best next actions</h2></div>{user&&<button className="smallButton" onClick={()=>openComposer('opportunity')}>Add opportunity</button>}</div><div className="stack">{ranked.length?ranked.map(o=><article className="op" key={o.id}><div><span className="evidence">{o.evidence} · {evidenceLabels[o.evidence]}</span><h3>{o.title}</h3><p>{o.observation}</p><SourceLink url={o.sourceUrl}/></div><strong title="Priority score">{score(o)}</strong></article>):<p className="empty">No saved opportunities yet.</p>}</div></div><div className="panel"><div className="panelHead"><div><p className="eyebrow">RISK CENTER</p><h2>What could hurt us?</h2></div>{user&&<button className="smallButton" onClick={()=>openComposer('risk')}>Add risk</button>}</div><div className="stack">{record.risks.length?record.risks.map(r=><article className="miniCard" key={r.id}><div className="miniHead"><b>{r.title}</b><span className={'risk '+r.level.toLowerCase()}>{r.level}</span></div><p>{r.response}</p><small>{r.evidence} · {evidenceLabels[r.evidence]}</small><SourceLink url={r.sourceUrl}/></article>):<p className="empty">No saved risks yet.</p>}</div></div></section>
  <section className="panel" id="decisions"><div className="panelHead"><div><p className="eyebrow">DECISION ENGINE</p><h2>Choices worth remembering</h2></div>{user&&<button className="smallButton" onClick={()=>openComposer('decision')}>Add decision</button>}</div><div className="decisionGrid">{record.decisions.length?record.decisions.map(d=><article key={d.id}><span className="tag">{d.status}</span><h3>{d.question}</h3><p><b>Next:</b> {d.next}</p><small>{d.evidence} · {evidenceLabels[d.evidence]}</small><SourceLink url={d.sourceUrl}/></article>):<p className="empty">No saved decisions yet.</p>}</div></section>
  <section className="panel" id="memory"><div className="panelHead"><div><p className="eyebrow">BUSINESS MEMORY</p><h2><Term>Business Memory</Term></h2></div>{user&&<button className="smallButton" onClick={()=>openComposer('memory')}>Add founder note</button>}</div><div className="timeline">{record.memory.length?record.memory.map(m=><article key={m.id}><time>{m.date}</time><div><b>{m.kind}</b><p>{m.summary}</p><small>{m.evidence} · {evidenceLabels[m.evidence]}</small><SourceLink url={m.sourceUrl}/></div></article>):<p className="empty">No memory entries yet.</p>}</div></section>
  <section className="panel neighborhood" id="sales"><div><p className="eyebrow">CUSTOMERS & GROWTH → SALES</p><h2>Same-Day Customer Growth Pack / Sales OS</h2><p>Sales remains a major connected module for prospect research, outreach, follow-up and <Term>CRM</Term> history. It lives inside Customers & Growth, where it belongs.</p></div><a className="moduleLink" href="/sales-engine-app/">Open Sales OS →</a></section>
  {composer&&<div className="modalBackdrop" role="presentation" onMouseDown={()=>setComposer(null)}><form className="recordComposer" onSubmit={saveComposer} onMouseDown={e=>e.stopPropagation()}><div className="composerHead"><div><p className="eyebrow">ADD TO THE SHARED BUSINESS RECORD</p><h2>{composer.kind==='memory'?'Add a founder note':`Add ${composer.kind}`}</h2></div><button type="button" className="closeButton" onClick={()=>setComposer(null)}>×</button></div><label>{composer.kind==='decision'?'Decision to make':composer.kind==='memory'?'Type of note':'Short title'}<input required value={composer.title} onChange={e=>setComposer({...composer,title:e.target.value})}/></label><label>{composer.kind==='decision'?'What should happen next?':composer.kind==='risk'?'How should the business respond?':composer.kind==='memory'?'What happened or what did you learn?':'Why does this matter?'}<textarea required value={composer.detail} onChange={e=>setComposer({...composer,detail:e.target.value})}/></label>{composer.kind==='value'&&<label>Type<select value={composer.category} onChange={e=>setComposer({...composer,category:e.target.value})}><option>Created</option><option>Captured</option><option>Leak</option><option>At Risk</option><option>Opportunity</option><option>Asset</option></select></label>}{composer.kind==='risk'&&<label>How serious is it?<select value={composer.category} onChange={e=>setComposer({...composer,category:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select></label>}{composer.kind==='opportunity'&&<label>How confident are you right now? <span>{composer.category}%</span><input type="range" min="0" max="100" value={composer.category} onChange={e=>setComposer({...composer,category:e.target.value})}/></label>}<p className="formNote">Manual founder entries are saved as E4 Internal Observation. That means “we recorded this,” not “the market proved this.”</p><div className="reviewButtons"><button disabled={busy}>Save to business record</button><button type="button" className="rejectButton" onClick={()=>setComposer(null)}>Cancel</button></div></form></div>}
  <footer>Founder Dynasty OS 10.0 · A SMARTPICKSHOP HOLDINGS PRODUCT · Evidence-linked operating intelligence</footer>
 </main>;
}
