<?php
if (!defined('ABSPATH')) exit;

class FDOS_VLS_DB {
    const DB_VERSION='1.0.1';

    public static function activate(){self::install();}
    public static function maybe_upgrade(){if(get_option('fdos_vls_db_version')!==self::DB_VERSION) self::install();}
    private static function install(){
        global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate();
        $i=$wpdb->prefix.'fdos_intakes'; $e=$wpdb->prefix.'fdos_evidence_events'; $x=$wpdb->prefix.'fdos_experiments'; $q=$wpdb->prefix.'fdos_qa_runs';
        dbDelta("CREATE TABLE $i (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, public_id CHAR(36) NOT NULL, website_url TEXT NULL, facebook_url TEXT NULL, business_idea LONGTEXT NULL, email_hash CHAR(64) NULL, findings_json LONGTEXT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id), UNIQUE KEY public_id(public_id)) $c;");
        dbDelta("CREATE TABLE $e (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,event_id CHAR(36) NOT NULL,dedupe_key VARCHAR(191) NULL,intake_public_id CHAR(36) NULL,experiment_id CHAR(36) NULL,event_type VARCHAR(100) NOT NULL,project VARCHAR(191) NULL,channel VARCHAR(100) NULL,campaign VARCHAR(191) NULL,numeric_value DECIMAL(20,4) NULL,currency CHAR(3) NULL,evidence_class CHAR(2) NOT NULL,confidence TINYINT UNSIGNED NOT NULL DEFAULT 0,source_type VARCHAR(100) NULL,source_ref TEXT NULL,metadata LONGTEXT NULL,occurred_at DATETIME NOT NULL,recorded_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY event_id(event_id),UNIQUE KEY dedupe_key(dedupe_key),KEY event_type(event_type),KEY experiment_id(experiment_id)) $c;");
        dbDelta("CREATE TABLE $x (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,experiment_id CHAR(36) NOT NULL,name VARCHAR(191) NOT NULL,hypothesis LONGTEXT NULL,primary_kpi VARCHAR(100) NOT NULL,guardrails LONGTEXT NULL,baseline_start DATE NULL,baseline_end DATE NULL,observation_start DATE NULL,observation_end DATE NULL,status VARCHAR(20) NOT NULL DEFAULT 'draft',decision VARCHAR(40) NOT NULL DEFAULT 'pending',result_json LONGTEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY experiment_id(experiment_id),KEY status(status),KEY primary_kpi(primary_kpi)) $c;");
        dbDelta("CREATE TABLE $q (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,run_id CHAR(36) NOT NULL,plugin_version VARCHAR(32) NOT NULL,internal_status VARCHAR(20) NOT NULL,pass_count INT UNSIGNED NOT NULL DEFAULT 0,fail_count INT UNSIGNED NOT NULL DEFAULT 0,pending_count INT UNSIGNED NOT NULL DEFAULT 0,report_json LONGTEXT NULL,ran_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY run_id(run_id),KEY ran_at(ran_at),KEY internal_status(internal_status)) $c;");
        update_option('fdos_vls_db_version',self::DB_VERSION,false);
    }
    public static function uuid(){return wp_generate_uuid4();}
    public static function table_exists($suffix){global $wpdb;$t=$wpdb->prefix.$suffix;return $wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))===$t;}
    public static function insert_intake($d){global $wpdb;$id=self::uuid();$wpdb->insert($wpdb->prefix.'fdos_intakes',['public_id'=>$id,'website_url'=>$d['website_url']??null,'facebook_url'=>$d['facebook_url']??null,'business_idea'=>$d['business_idea']??null,'email_hash'=>$d['email_hash']??null,'findings_json'=>wp_json_encode($d['findings']??[]),'created_at'=>current_time('mysql',true)]);return $id;}
    public static function insert_event($d){global $wpdb;$dedupe=$d['dedupe_key']??null;if($dedupe&&($x=self::find_event_by_dedupe_key($dedupe)))return $x;$event=self::uuid();$wpdb->insert($wpdb->prefix.'fdos_evidence_events',['event_id'=>$event,'dedupe_key'=>$dedupe,'intake_public_id'=>$d['intake_public_id']??null,'experiment_id'=>$d['experiment_id']??null,'event_type'=>$d['event_type'],'project'=>$d['project']??null,'channel'=>$d['channel']??null,'campaign'=>$d['campaign']??null,'numeric_value'=>$d['numeric_value']??null,'currency'=>$d['currency']??null,'evidence_class'=>$d['evidence_class']??'E4','confidence'=>(int)($d['confidence']??0),'source_type'=>$d['source_type']??null,'source_ref'=>$d['source_ref']??null,'metadata'=>wp_json_encode($d['metadata']??[]),'occurred_at'=>$d['occurred_at']??current_time('mysql',true),'recorded_at'=>current_time('mysql',true)]);return $wpdb->insert_id?$event:false;}
    public static function find_event_by_dedupe_key($k){global $wpdb;return $wpdb->get_var($wpdb->prepare("SELECT event_id FROM {$wpdb->prefix}fdos_evidence_events WHERE dedupe_key=%s LIMIT 1",$k));}
    public static function metric_window($type,$start,$end,$exp=null){global $wpdb;$sql="SELECT COUNT(*) c,SUM(COALESCE(numeric_value,1)) v FROM {$wpdb->prefix}fdos_evidence_events WHERE event_type=%s AND DATE(occurred_at) BETWEEN %s AND %s";$args=[$type,$start,$end];if($exp){$sql.=' AND experiment_id=%s';$args[]=$exp;}$r=$wpdb->get_row($wpdb->prepare($sql,...$args),ARRAY_A);return ['count'=>(int)($r['c']??0),'value'=>(float)($r['v']??0)];}
    public static function experiment_event_count($id){global $wpdb;return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}fdos_evidence_events WHERE experiment_id=%s",$id));}
    public static function insert_experiment($d){global $wpdb;$id=self::uuid();$now=current_time('mysql',true);$wpdb->insert($wpdb->prefix.'fdos_experiments',['experiment_id'=>$id,'name'=>$d['name'],'hypothesis'=>$d['hypothesis']??'','primary_kpi'=>$d['primary_kpi'],'guardrails'=>wp_json_encode($d['guardrails']??[]),'baseline_start'=>$d['baseline_start']??null,'baseline_end'=>$d['baseline_end']??null,'observation_start'=>$d['observation_start']??null,'observation_end'=>$d['observation_end']??null,'status'=>$d['status']??'draft','decision'=>$d['decision']??'pending','result_json'=>isset($d['result_json'])?wp_json_encode($d['result_json']):null,'created_at'=>$now,'updated_at'=>$now]);return $wpdb->insert_id?$id:false;}
    public static function get_experiment($id){global $wpdb;$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}fdos_experiments WHERE experiment_id=%s LIMIT 1",$id),ARRAY_A);if(!$r)return null;foreach(['guardrails','result_json'] as $k)if(isset($r[$k]))$r[$k]=json_decode($r[$k],true);return $r;}
    public static function update_experiment($id,$d){global $wpdb;$m=[];foreach(['name','hypothesis','primary_kpi','baseline_start','baseline_end','observation_start','observation_end','status','decision'] as $k)if(array_key_exists($k,$d))$m[$k]=$d[$k];if(array_key_exists('guardrails',$d))$m['guardrails']=wp_json_encode($d['guardrails']);if(array_key_exists('result_json',$d))$m['result_json']=wp_json_encode($d['result_json']);$m['updated_at']=current_time('mysql',true);return $wpdb->update($wpdb->prefix.'fdos_experiments',$m,['experiment_id'=>$id])!==false;}
    public static function list_experiments($limit=50,$status=''){global $wpdb;$limit=max(1,min(100,(int)$limit));if($status)return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}fdos_experiments WHERE status=%s ORDER BY updated_at DESC LIMIT %d",$status,$limit),ARRAY_A);return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}fdos_experiments ORDER BY updated_at DESC LIMIT %d",$limit),ARRAY_A);}
    public static function intake_count(){global $wpdb;return (int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}fdos_intakes");}
    public static function recent_events($limit=25){global $wpdb;$limit=max(1,min(100,(int)$limit));return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->prefix}fdos_evidence_events ORDER BY recorded_at DESC LIMIT %d",$limit),ARRAY_A);}
    public static function evidence_mix(){global $wpdb;$rows=$wpdb->get_results("SELECT evidence_class,COUNT(*) c FROM {$wpdb->prefix}fdos_evidence_events GROUP BY evidence_class",ARRAY_A);$out=array_fill_keys(array_keys(FDOS_VLS_Engine::EVIDENCE_CLASSES),0);foreach($rows as $r)$out[$r['evidence_class']]=(int)$r['c'];return $out;}
    public static function funnel_summary(){global $wpdb;$types=['scanner_completed','scanner_result_viewed','value_sprint_cta_clicked','lead_cta_clicked','shopify_outbound_clicked','shopify_order_created','shopify_order_paid'];$out=[];foreach($types as $t){$r=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) c,SUM(COALESCE(numeric_value,0)) v FROM {$wpdb->prefix}fdos_evidence_events WHERE event_type=%s",$t),ARRAY_A);$out[$t]=['count'=>(int)$r['c'],'value'=>(float)$r['v']];}return $out;}
    public static function experiment_summary($limit=20){return self::list_experiments($limit);}
    public static function latest_ranked_finding(){global $wpdb;$row=$wpdb->get_row("SELECT findings_json FROM {$wpdb->prefix}fdos_intakes ORDER BY created_at DESC LIMIT 1",ARRAY_A);if(!$row)return null;$f=json_decode($row['findings_json'],true);return is_array($f)&&$f?reset($f):null;}
    public static function command_center_snapshot(){return ['intakes'=>self::intake_count(),'funnel'=>self::funnel_summary(),'evidence_mix'=>self::evidence_mix(),'recent_events'=>self::recent_events(25),'experiments'=>self::experiment_summary(20),'next_ranked_action'=>self::latest_ranked_finding(),'generated_at'=>current_time('mysql',true)];}
    public static function latest_shopify_webhook_event(){global $wpdb;$r=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}fdos_evidence_events WHERE source_type='shopify_verified_webhook' AND event_type IN ('shopify_order_created','shopify_order_paid') ORDER BY recorded_at DESC LIMIT 1",ARRAY_A);if($r)$r['metadata']=json_decode($r['metadata'],true);return $r;}
    public static function count_shopify_verified_webhooks(){global $wpdb;return (int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}fdos_evidence_events WHERE source_type='shopify_verified_webhook'");}
    public static function insert_qa_run($r){global $wpdb;$wpdb->insert($wpdb->prefix.'fdos_qa_runs',['run_id'=>$r['run_id'],'plugin_version'=>FDOS_VLS_VERSION,'internal_status'=>$r['internal_status'],'pass_count'=>$r['pass_count'],'fail_count'=>$r['fail_count'],'pending_count'=>$r['pending_count'],'report_json'=>wp_json_encode($r),'ran_at'=>current_time('mysql',true)]);return $wpdb->insert_id;}
    public static function latest_qa_run(){global $wpdb;$r=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}fdos_qa_runs ORDER BY ran_at DESC LIMIT 1",ARRAY_A);if($r)$r['report_json']=json_decode($r['report_json'],true);return $r;}
    public static function delete_qa_records(){global $wpdb;return $wpdb->query("DELETE FROM {$wpdb->prefix}fdos_evidence_events WHERE source_type='fdos_qa'");}
    public static function qa_records_remaining(){global $wpdb;return (int)$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}fdos_evidence_events WHERE source_type='fdos_qa'");}
    public static function export_snapshot(){global $wpdb;return ['format'=>'fdos-export/v1','plugin_version'=>FDOS_VLS_VERSION,'db_version'=>self::DB_VERSION,'exported_at'=>current_time('mysql',true),'intakes'=>$wpdb->get_results("SELECT * FROM {$wpdb->prefix}fdos_intakes",ARRAY_A),'evidence_events'=>$wpdb->get_results("SELECT * FROM {$wpdb->prefix}fdos_evidence_events",ARRAY_A),'experiments'=>$wpdb->get_results("SELECT * FROM {$wpdb->prefix}fdos_experiments",ARRAY_A),'qa_runs'=>$wpdb->get_results("SELECT * FROM {$wpdb->prefix}fdos_qa_runs",ARRAY_A)];}
    public static function retention_cleanup($browser_days=0,$intake_days=0,$qa_days=180){global $wpdb;$out=['browser_events'=>0,'intakes'=>0,'qa_runs'=>0];if($browser_days>0)$out['browser_events']=(int)$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->prefix}fdos_evidence_events WHERE source_type='first_party_browser_event' AND recorded_at < DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY)",$browser_days));if($intake_days>0){$ids=$wpdb->get_col($wpdb->prepare("SELECT public_id FROM {$wpdb->prefix}fdos_intakes WHERE created_at < DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY)",$intake_days));if($ids){foreach($ids as $id)$wpdb->delete($wpdb->prefix.'fdos_evidence_events',['intake_public_id'=>$id]);}$out['intakes']=(int)$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->prefix}fdos_intakes WHERE created_at < DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY)",$intake_days));}if($qa_days>0)$out['qa_runs']=(int)$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->prefix}fdos_qa_runs WHERE ran_at < DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY)",$qa_days));return $out;}
}
