<?php
if (!defined('ABSPATH')) exit;

class FDOS_VLS_Live_Evidence {
    public static function audit($url){
        $url=esc_url_raw($url);
        if(!$url) return ['findings'=>[[ 'key'=>'invalid_url','observation'=>'The submitted website URL was invalid.','evidence'=>'E4','confidence'=>100,'priority_score'=>0,'action'=>'Provide a valid public HTTP(S) URL.' ]]];
        $parts=wp_parse_url($url);$host=strtolower($parts['host']??'');$scheme=strtolower($parts['scheme']??'');
        if(!in_array($scheme,['http','https'],true)||!$host||$host==='localhost'||substr($host,-6)==='.local') return ['findings'=>[[ 'key'=>'unsafe_target','observation'=>'FDOS refused to retrieve a local or unsupported target.','evidence'=>'E4','confidence'=>100,'priority_score'=>0,'action'=>'Use a public HTTP(S) website.' ]]];
        $ips=gethostbynamel($host)?:[];foreach($ips as $ip)if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))return ['findings'=>[[ 'key'=>'unsafe_target','observation'=>'FDOS refused to retrieve a private or reserved network target.','evidence'=>'E4','confidence'=>100,'priority_score'=>0,'action'=>'Use a public website.' ]]];
        $r=wp_safe_remote_get($url,['timeout'=>8,'redirection'=>3,'limit_response_size'=>1048576,'user-agent'=>'Founder Dynasty OS/1.0']);
        if(is_wp_error($r)) return ['findings'=>[[ 'key'=>'retrieval_failed','observation'=>'FDOS could not retrieve the submitted public website.','evidence'=>'E4','confidence'=>95,'priority_score'=>40,'action'=>'Verify the URL is public and reachable, then retry.' ]]];
        $code=(int)wp_remote_retrieve_response_code($r);$type=strtolower((string)wp_remote_retrieve_header($r,'content-type'));$body=(string)wp_remote_retrieve_body($r);
        if(strpos($type,'html')===false&&strpos($type,'xhtml')===false) return ['findings'=>[[ 'key'=>'non_html','observation'=>'The submitted URL returned non-HTML content.','evidence'=>'E2','confidence'=>100,'priority_score'=>35,'action'=>'Scan a public HTML landing page instead.','source_ref'=>$url ]]];
        $title='';$description='';$h1=[];$viewport=false;$canonical=false;$jsonld=false;$forms=0;$mailto=false;$tel=false;$ctas=[];
        if(class_exists('DOMDocument')){libxml_use_internal_errors(true);$d=new DOMDocument();@$d->loadHTML($body,LIBXML_NONET|LIBXML_NOWARNING|LIBXML_NOERROR);libxml_clear_errors();$xp=new DOMXPath($d);$t=$d->getElementsByTagName('title');if($t->length)$title=trim($t->item(0)->textContent);foreach($d->getElementsByTagName('meta') as $m){$n=strtolower($m->getAttribute('name'));if($n==='description')$description=trim($m->getAttribute('content'));if($n==='viewport')$viewport=true;}foreach($d->getElementsByTagName('h1') as $n)$h1[]=trim($n->textContent);foreach($d->getElementsByTagName('link') as $n)if(strtolower($n->getAttribute('rel'))==='canonical')$canonical=true;foreach($d->getElementsByTagName('script') as $n)if(stripos($n->getAttribute('type'),'ld+json')!==false)$jsonld=true;$forms=$d->getElementsByTagName('form')->length;foreach($d->getElementsByTagName('a') as $a){$href=strtolower($a->getAttribute('href'));if(strpos($href,'mailto:')===0)$mailto=true;if(strpos($href,'tel:')===0)$tel=true;$txt=trim(preg_replace('/\s+/',' ',$a->textContent));if($txt&&preg_match('/\b(buy|shop|start|get|book|contact|quote|demo|subscribe|join|sign up|learn more)\b/i',$txt))$ctas[]=$txt;}}
        else {preg_match('/<title[^>]*>(.*?)<\/title>/is',$body,$m);$title=trim(wp_strip_all_tags($m[1]??''));$viewport=(bool)preg_match('/<meta[^>]+name=["\']viewport["\']/i',$body);$canonical=(bool)preg_match('/<link[^>]+rel=["\']canonical["\']/i',$body);$jsonld=(bool)preg_match('/application\/ld\+json/i',$body);$forms=preg_match_all('/<form\b/i',$body);$mailto=stripos($body,'mailto:')!==false;$tel=stripos($body,'tel:')!==false;}
        $f=[];$add=function($key,$obs,$confidence,$action,$inputs=[])use(&$f,$url){$f[]=['key'=>$key,'observation'=>$obs,'evidence'=>'E2','confidence'=>$confidence,'priority_score'=>FDOS_VLS_Engine::opportunity_score($inputs?:['impact'=>6,'evidence_strength'=>9,'speed'=>8,'reversibility'=>9,'cost'=>2,'complexity'=>3,'risk'=>2]),'action'=>$action,'source_ref'=>$url];};
        $add('retrieval_status',"The submitted page returned HTTP {$code} and was parsed as HTML.",100,'Use the retrieved page as a technical baseline; business impact still requires measurement.',['impact'=>4,'evidence_strength'=>10,'speed'=>10,'reversibility'=>10,'cost'=>1,'complexity'=>1,'risk'=>1]);
        if(!$title)$add('missing_title','No HTML title was observed on the retrieved page.',98,'Add a concise descriptive page title and measure downstream engagement/search effects rather than assuming impact.');
        if(!$description)$add('missing_meta_description','No meta description was observed on the retrieved page.',95,'Add a clear description aligned with the page offer and measure click/engagement effects.');
        if(!$viewport)$add('missing_viewport','No viewport meta tag was observed.',98,'Add an appropriate viewport declaration and verify mobile rendering on real devices.');
        if(count($h1)===0)$add('missing_h1','No H1 element was observed on the retrieved page.',95,'Add one clear primary page heading and test comprehension.');
        if(count($h1)>1)$add('multiple_h1','Multiple H1 elements were observed on the retrieved page.',90,'Review heading hierarchy for clarity; do not assume an SEO penalty without evidence.');
        if(!$forms&&!$mailto&&!$tel&&!$ctas)$add('no_conversion_path','FDOS did not observe a form, mailto/tel path, or recognizable CTA on the retrieved HTML.',92,'Add a clear next action tied to one measurable conversion event.',['impact'=>9,'evidence_strength'=>9,'speed'=>8,'reversibility'=>9,'cost'=>2,'complexity'=>3,'risk'=>2]);
        if(!$ctas)$add('no_recognizable_cta','No recognizable CTA text was observed in the retrieved link text.',88,'Test one explicit CTA aligned with the visitor’s next step.');
        if(!$jsonld)$add('no_jsonld','No JSON-LD structured data block was observed.',95,'Add appropriate structured data only where it accurately describes real page content.');
        if(!$canonical)$add('no_canonical','No canonical link element was observed.',95,'Review canonicalization needs and add a canonical URL where appropriate.');
        return ['findings'=>$f,'baseline'=>['http_status'=>$code,'content_type'=>$type,'bytes'=>strlen($body),'title'=>$title,'meta_description'=>$description,'h1_count'=>count($h1),'h1_examples'=>array_slice($h1,0,3),'viewport'=>$viewport,'canonical'=>$canonical,'json_ld'=>$jsonld,'forms'=>$forms,'mailto'=>$mailto,'tel'=>$tel,'cta_count'=>count($ctas),'cta_examples'=>array_slice(array_values(array_unique($ctas)),0,5)]];
    }
}
